### ISSUE TITLE
Not seeing the sushi?  🤔

### ISSUE THREAD

**Issue by ManjitBedi** [keijiro/SushiVfx#1]
Hi,

I have downloaded the sushi models and have copied them into the "Assets\DDD\J-food-4" folder.
I don't see anything change in the Unity scene files when I try them.  

I have looked at how the Vaporize scene is set up; I see there is a sushi game object.  Does it have a reference to a 3D model somewhere?

Do I need to delete any of the files as there is an OBJ and FBX in the folder?

**Comment by ManjitBedi** [comment]
I think I figured it out; I needed to move the assets into the folder first using the FBX model before loading the project into the Unity editor.

**Comment by keijiro** [comment]
Yes. Unity removes `.meta` files when the file body is missing.
