### ISSUE TITLE
Mesh sampling group not working.

### ISSUE THREAD

**Issue by blue2co** [keijiro/SushiVfx#2]
Hi!

I downloaded the sushi fbx file and applied it to the sample mesh, so it is not applied to the set position at all. set color is the same problem

please help me

![aaa](https://user-images.githubusercontent.com/50586236/153361150-3951b338-067d-4ba7-9140-c3f6fa0e6bb6.png)

**Comment by keijiro** [comment]
Did you put those asset files before opening the project?

The `.meta` files will be removed if you open the project without the asset files.

**Comment by blue2co** [comment]
thank you!! I understand why you put the meta file.
