### ISSUE TITLE
Where else is the mesh being referenced for Voxelize? (Aside from the mesh properties in VFXGraph)

### ISSUE THREAD

**Issue by MetaHertzLabs** [keijiro/SushiVfx#3]
I'd like to use the Voxelize effect for other meshes, I tried replacing the mesh in Base Mesh in the graph but after saving it hasn't updated, the color map did successfully recognize changes so it is saving properly. It appears the voxels look like maguro and are still linked to this maguro somewhere. Where else is the mesh being referenced for me to update the effect?

**Comment by keijiro** [comment]
I can't remember it correctly (it's 2 years ago!), but I think you should update SDF because those effects use the SDF. Please use Google (VFX Graph & SDF) for details -- Sorry, I can't explain it well in English.
